version: '3.3'

services:
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    depends_on:
      - jenkins
    environment:
      SONAR_JDBC_URL: "${SONAR_JDBC_URL}"
      SONAR_JDBC_USERNAME: "${SONAR_JDBC_USERNAME}"
      SONAR_JDBC_PASSWORD: "${SONAR_JDBC_PASSWORD}"

    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    networks:
      - devops-runner-network-team-02
    ports:
      - "3004:9000"
  
  db:
    image: postgres:12
    container_name: postgresql
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - devops-runner-network-team-02
  
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: always
    depends_on:
      - nexus
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - devops-runner-network-team-02
    ports:
      - "3001:8080"

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    restart: on-failure
    depends_on:
      - db
    volumes:
      - nexus-data:/sonatype-work sonatype/nexus
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops-runner-network-team-02
    ports:
      - "3002:8081"
  
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    depends_on:
      - sonarqube
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-data:/data
    networks:
      - devops-runner-network-team-02
    ports:
      - 3003:9000

volumes:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_data:
  postgresql:
  postgresql_data:
  jenkins:
  nexus-data:
  portainer-data:

networks:
  devops-runner-network-team-02:
    driver: bridge