version: '3.3'

services:
  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
    volumes:
      - ./containers/sonarqube/data:/opt/sonarqube/data
      - ./containers/sonarqube/extensions:/opt/sonarqube/extensions
      - ./containers/sonarqube/logs:/opt/sonarqube/logs
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops-runner-network-team-02
    ports:
      - "3000:80"
  
  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./containers/postgresql/conf:/var/lib/postgresql
      - ./containers/postgresql/data:/var/lib/postgresql/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops-runner-network-team-02
  
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    volumes:
      - ./containers/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops-runner-network-team-02
    ports:
      - "3001:8080"

  nexus:
    image: sonatype/nexus3
    container_name: nexus
    volumes:
      - ./containers/nexus-data:/sonatype-work
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops-runner-network-team-02
    ports:
      - "3002:80"
  
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./containers/portainer-data:/data
    networks:
      - devops-runner-network-team-02
    ports:
      - 3003:9000
  
  # init:
  #     image: bash
  #     privileged: true
  #     user: root
  #     volumes:
  #       - ./containers/init.sh:/mnt/init.sh
  #     command: ["sh", "-e", "/mnt/init.sh"]

networks:
  devops-runner-network-team-02:
    driver: bridge